### ISSUE TITLE
Stamina bar don't show fully information

### ISSUE THREAD

**Issue by EgzoT** [edubart/otclient#989]
**This is missing feature on client side relative to TFS.**

### Steps to reproduce
1. Check stamina bar.

### Expected behaviour
1. Stamina bar must show information from server (base TFS) to client side (bonuses/penalties from stamina).
2. Stamina bar need to change color on certain values, when time was change.
3. Stamina bar need to change tooltip on certain values, when time was change.

### Actual behaviour
1. Stamina bar have one (red) color.
2. Shows tooltip who show time in percent value.

### TODO list
- [ ] Change colors on certain values, when time was change.
- [ ] Change tooltip on certain values, when time was change.
- [ ] Multiprotocol.
- [ ] Check premium on some versions.
